apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
    pod-template-hash: 84bd47bf4
  name: mongodb-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
    pod-template-hash: 84bd47bf4
status:
  loadBalancer: {}
